//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/[[App]]/Scripts/VerseInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VerseInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VerseInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VerseInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""13a77f1b-ce03-4ac5-ae96-05aa1c9c656d"",
            ""actions"": [
                {
                    ""name"": ""VoiceBroadcastGlobal"",
                    ""type"": ""Button"",
                    ""id"": ""849b63f0-2a77-422b-9f52-673c0389d8f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b8182c0e-42fc-4539-bb5e-7c4d09c64420"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VoiceBroadcastGlobal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfa59ee8-b2be-4043-aa96-b7d34ea9eba1"",
                    ""path"": ""<WebXRControllerRight>/primaryButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VoiceBroadcastGlobal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d366ee98-2199-4e38-9123-91048e8ee173"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VoiceBroadcastGlobal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_VoiceBroadcastGlobal = m_Player.FindAction("VoiceBroadcastGlobal", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_VoiceBroadcastGlobal;
    public struct PlayerActions
    {
        private @VerseInputActions m_Wrapper;
        public PlayerActions(@VerseInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @VoiceBroadcastGlobal => m_Wrapper.m_Player_VoiceBroadcastGlobal;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @VoiceBroadcastGlobal.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVoiceBroadcastGlobal;
                @VoiceBroadcastGlobal.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVoiceBroadcastGlobal;
                @VoiceBroadcastGlobal.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVoiceBroadcastGlobal;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @VoiceBroadcastGlobal.started += instance.OnVoiceBroadcastGlobal;
                @VoiceBroadcastGlobal.performed += instance.OnVoiceBroadcastGlobal;
                @VoiceBroadcastGlobal.canceled += instance.OnVoiceBroadcastGlobal;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnVoiceBroadcastGlobal(InputAction.CallbackContext context);
    }
}
